# Identity Reconciliation Service Configuration
server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: identity-reconciliation-service
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:file:./data/identity_reconciliation;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  # H2 Console Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop  # Changed to create-drop for development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true  # This ensures data.sql runs AFTER schema creation

  # SQL Initialization
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

# Logging Configuration
logging:
  level:
    com.moonrider.identityreconciliation: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/identity-reconciliation.log

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Custom Application Properties
app:
  name: Identity Reconciliation Service
  version: 1.0.0
  description: Covert identity reconciliation system for customer contact consolidation

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.moonrider.identityreconciliation: DEBUG
    org.springframework.web: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.moonrider.identityreconciliation: WARN
    root: WARN